# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buffer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='private',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='text',
            name='public',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
